language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4.4"
  - "5.11"
  - "6.1"

before_install:
  - npm install -g npm

install:
  - npm install

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
